version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '5775:5775'
      - '6831:6831'
      - '6832:6832'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      -  ALLOW_PLAINTEXT_LISTENER=yes