version: "3.8"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '5775:5775'
      - '6831:6831'
      - '6832:6832'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CREATE_TOPICS=my-topic:1:1
    depends_on:
      - zookeeper